- type: job
  id: BKBPLATech
  name: job-name-silicon-BPLATech
  description: job-description-silicon-BPLATech
  playTimeTracker: BPLATech
  joinNotifyCrew: false
  icon: JobIconUnknown
  supervisors: job-supervisors-human
  canBeAntag: false
  jobEntity: DroneBPLA
  startingGear: RobotGear # for char preview only
  whitelisted: true
  discordRequired: true

- type: startingGear
  id: RobotGear
  equipment:
    head: ClothingHeadHatCardborg
    outerClothing: ClothingOuterCardborg
